### PR TITLE
translate upgrade guide for zh-tw

### PR DESCRIPTION
**Pull request by appleboy**
Also provide a backport to v1.0 branch.

cc @lunny @tboerger

### CODE REVIEW

**Comment by lunny** [comment]
The target branch is master?

**Comment by appleboy** [comment]
@lunny Yes, merge to master first. I will create another PR for v1.0 branch if this PR has been merged.

**Comment by lunny** [comment]
LGTM

**Comment by strk** [comment]
LGTM

**Comment by lunny** [comment]
let L-G-T-M work

**Comment by lunny** [comment]
Drone is always waiting......

**Pull request merged**
