### PR TITLE
Fixed localization and added content

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Requires the theme changes at https://github.com/go-gitea/theme/pull/16

**Comment by Bwko** [comment]
LGTM

**Comment by tboerger** [comment]
Build fixed

**Review by bkcsoft — CHANGES_REQUESTED** [review]
Same here as for https://github.com/go-gitea/website/pull/14, shouldn't give false hopes. 😉 

I can translate this to Swedish if we need an "example for how to translate" :)

**Comment by tboerger** [comment]
But Chinese is already prepared. Swedish needs preparation within the theme repo first.

**Comment by bkcsoft** [comment]
@tboerger it was more about not having English text in the Chinese version 🙂

**Comment by tboerger** [comment]
But as you know the pages are work on progress, we need to start somewhere

**Comment by metalmatze** [comment]
LGTM

**Review by bkcsoft — APPROVED** [review]

**Comment by lunny** [comment]
https://github.com/go-gitea/docs/pull/12

**Pull request merged**
