### PR TITLE
Improve cheat sheet for COOKIE_NAME

### PR DESCRIPTION
**Pull request by sztanpet**
Also normalize the line endings to `\n` (Unix)

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by thibaultmeyer** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by lunny** [comment]
@sztanpet could you send a back port to release/v1.0?

**Comment by sztanpet** [comment]
I think so, as a separate PR right?

**Comment by tboerger** [comment]
> I think so, as a separate PR right?

Right

**Comment by tboerger** [comment]
Backported via https://github.com/go-gitea/docs/pull/64

**Pull request merged**
