### PR TITLE
docs: improve document.

### PR DESCRIPTION
**Pull request by appleboy**
ref: https://github.com/go-gitea/gitea/pull/577

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by tboerger** [comment]
Not because of that, we suggest 1.6 because we are using vendoring and we don't set the required env variable for 1.5 anywhere

**Comment by appleboy** [comment]
@tboerger Good catch.

**Comment by appleboy** [comment]
@tboerger @lunny Review again.

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
