### PR TITLE
Add mssql driver on docs

### PR DESCRIPTION
**Pull request by lunny**
But this feature will be released in v1.1

### CODE REVIEW

**Comment by bkcsoft** [comment]
LGTM

**Comment by bkcsoft** [comment]
Maybe we need to start versioning our docs 😛

**Comment by lunny** [comment]
But for user how to which feature is 1.0 or 1.1? We need to define it not only in issues

**Comment by tboerger** [comment]
I asked for this at the beginning. There are two ways.

1) only document latest version 
2) simply tag the docs and build docker containers for these who need older versions

**Comment by lunny** [comment]
I like 2

**Comment by andreynering** [comment]
LGTM

**Comment by tboerger** [comment]
So before a merge we need to tweak the drone config, tag 1.0.0 and than the new features can get documented.

**Comment by appleboy** [comment]
Vote 2. Sound like make sense.

**Comment by lunny** [comment]
One contanier is need maybe, use different sub path, root path -> docs master, others are branches or tags(which is better? I prefer branches).
```
https://docs.gitea.io/
https://docs.gitea.io/1.0
https://docs.gitea.io/1.1
```

**Comment by appleboy** [comment]
Using branches is better than Tag for maintenance. We can refer to laravel docs repo. https://github.com/laravel/docs

**Comment by tboerger** [comment]
And how do you want to generate the version switch if every release got a separate branch?

**Comment by lunny** [comment]
List branches of this repo? :)

**Comment by tboerger** [comment]
On a static page...

**Comment by lunny** [comment]
We could generated it before hugo and after git clone.
```
git clone
git branch > a.txt
hugo build
```

**Comment by tboerger** [comment]
Now there are more places that mention the database support :)

**Comment by lunny** [comment]
L-G-T-M

**Pull request merged**
