### PR TITLE
fix 404

### PR DESCRIPTION
**Pull request by luffyke**
1. fix 404 for [从源代码安装](https://docs.gitea.io/zh-cn/hacking-on-gitea/zh-cn/installation/from-source) in [Hacking on Gitea](https://docs.gitea.io/zh-cn/hacking-on-gitea/) page.

### CODE REVIEW

**Comment by lunny** [comment]
You have to cherry-pick and push force.

**Comment by tboerger** [comment]
As commented on https://github.com/go-gitea/docs/pull/71/files#r96233751 the linking is generally wrong. https://gohugo.io/extras/crossreferences/ shows how to properly link pages.

**Comment by luffyke** [comment]
wrong action was done by me, pr closed.

**Comment by lunny** [comment]
The commit should be sent via a new PR.

**Pull request closed without merging**
