### PR TITLE
Flesh out Docker instructions a bit.

### PR DESCRIPTION
**Pull request by morrildl**
Specifically, add steps to create a database for the Gitea container to use.

### CODE REVIEW

**Comment by morrildl** [comment]
I've tested the instructions in this PR verbatim on Ubuntu 16.04, and they work there, at least.

**Comment by morrildl** [comment]
LOL, oops, I overlooked #94. This is redundant with that PR, my bad.

**Comment by andreynering** [comment]
@morrildl @KangoV Thank you for your PRs. Improvements to documentation are always welcome.

I think that #94 and #95 should be merged in a single PR. One of them can be closed and other improved with changes made by the first. Thoughts?

**Comment by morrildl** [comment]
Sure, sounds reasonable. I'll close this PR.

**Pull request closed without merging**
