### PR TITLE
Add SSH_DOMAIN.

### PR DESCRIPTION
**Pull request by appleboy**
Ref: https://github.com/go-gitea/gitea/issues/552#issuecomment-273058538

cc @lunny @tboerger

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by bkcsoft** [comment]
LGTM

**Comment by bkcsoft** [comment]
make L-G-T-M work!

**Comment by lunny** [comment]
@appleboy please send back port

**Comment by appleboy** [comment]
@lunny @bkcsoft  https://github.com/go-gitea/docs/pull/78

**Pull request merged**
