### PR TITLE
Specify that Gogs 0.9.113 can be smootlhy upgraded to

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by strk** [comment]
```
13:18 < tboerger> To check if you can upgrade you got to monitor the migrations AND the models because of the xorm sync method which syncs the
                  model structs to the database
13:19 < tboerger> So every new struct attribute can possibly break the upgrade path
```

Do not merge this yet, it's not confirmed and should be tested.

BTW, 0.9.99 does not exist as a tag in Gogs, so eventually it should be 0.9.97

**Comment by lunny** [comment]
conflict

**Comment by tboerger** [comment]
Beside that all the useless line breaks...

**Comment by strk** [comment]
Unless someone checks the upgrade this has to be confirmed anyway

**Comment by Bwko** [comment]
Upgrading from `0.9.115.0103` works like a charm

**Comment by strk** [comment]
@Bwko greatest tag is `v0.9.113`, how can anyone know what `0.9.115.0103` is ?

**Comment by strk** [comment]
Well, written 0.9.115.0103 and fixed conflicts

**Comment by strk** [comment]
Better, left 0.9.115 and dropped the rest, done in all languages

**Comment by Bwko** [comment]
@strk Cause that's the [version at the bottom of your screen](https://github.com/gogits/gogs/blob/master/gogs.go#L20) (not released yet). But I agree 0.9.115 looks better

**Comment by Bwko** [comment]
LGTM

**Comment by appleboy** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Pull request merged**
