### PR TITLE
Add API documentation link

### PR DESCRIPTION
**Pull request by sapk**
Add a link to the swagger-ui on try.gitea.io in the top menu.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
But there some errors on https://try.gitea.io/swagger page.

**Comment by sapk** [comment]
@lunny go-gitea/gitea#1727 fix this (a loop in an object) and need one more LGT-M ^^

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Pull request merged**
