### PR TITLE
Improve cheat sheet for SSH_LISTEN_PORT

### PR DESCRIPTION
**Pull request by mkuhlmann**
Added `SSH_LISTEN_PORT` to cheat sheet, as proposed by go-gitea/gitea#603.

Comes with go-gitea/gitea#607.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by Bwko** [comment]
LGTM

**Comment by lunny** [comment]
Please back port to 1.0

**Comment by tboerger** [comment]
Is the backport already done?

**Comment by lunny** [comment]
I think no

**Comment by mkuhlmann** [comment]
Sorry, was away for 2 days. Backported in #67.

**Pull request merged**
