### PR TITLE
Create config-cheat-sheet.en-us.md

### PR DESCRIPTION
**Pull request by termlimit**
Didn't see the config cheat sheet on gitea.io. Updated, left the one Gogs reference as it is specific to an issue.

### CODE REVIEW

**Comment by lunny** [comment]
Great work and LGTM.

**Comment by tboerger** [comment]
I have intentionally skipped this doc because it always gets out of sync. I would prefer more comments within the app.ini and just link to it from the docs.

**Comment by termlimit** [comment]
Sounds good.

**Comment by appleboy** [comment]
@tboerger agree.

**Comment by lunny** [comment]
But if that in app.ini, how to translate it?

**Comment by bkcsoft** [comment]
@lunny maybe have multiple `app.ini`? since it will be embedded in the future (or is now, not sure)

**Comment by lunny** [comment]
We can make docs version so that the outdate problem will be resolved. Put it in app.ini will result in multi-language, a ton of question is about what the ini config item means because not every one know English. So I support merge this PR.

**Comment by tboerger** [comment]
But if somebody don't speak English he's anyway not being able to configure gitea as the variables are named English ;)

**Comment by tboerger** [comment]
Beside that, the header is missing multiple values, it won't work like it is.

**Comment by andreynering** [comment]
I like having this in the docs. We can have more detailed information than comments on app.ini

People could also ask questions and give more info on Discus comments. 

And there's also translations that lunny mentioned.

**Comment by termlimit** [comment]
Could we have different versions in the doc for reference? Have major updates increment to a new version. This should help address @tboerger comments and allow for slow adopters to troubleshoot. cake PHP has this type of nav in the [cookbook](http://book.cakephp.org/3.0/en/index.html) easy to switch to a different version.

Is there anyway to make the CI function check app.ini for changes and look at the corresponding doc page to notify an update is needed?

**Comment by tboerger** [comment]
LGTM for now, but somebody needs to check if it is really up2date.

**Pull request merged**
