### PR TITLE
Add instructions to install FreeBSD port/pkg

### PR DESCRIPTION
**Pull request by stblassitude**
Instructions for installing binary package or compiling the port manually.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM, thanks!

**Comment by tboerger** [comment]
LGTM

**Comment by Takika** [comment]
If you want to install with redis, you have to set GO_TAGS variable to 'redis' before the package creation.

**Comment by tboerger** [comment]
@Takika but gitea doesn't provide any build tag like that.

**Pull request merged**
