### PR TITLE
Create a new "Customizing Gitea" page under Advanced

### LINKED ISSUE #66: Mention that /robots.txt can be managed by the user
Willing to do the work of documenting the feature, but looking for guidance on where to do so.
The config cheat sheet does not seem appropriate for this.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40797065-mention-that-robots-txt-can-be-managed-by-the-user?utm_campaign=plugin&utm_content=tracker%2F47955789&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F47955789&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sztanpet**
* Create a new "Customizing Gitea" page under Advanced

For now, the only customization documented is the /robots.txt one.
Fixes #66 (backport)

* Mention to restart Gitea when changing custom/robots.txt

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by lunny** [comment]
Please rebase

**Comment by sztanpet** [comment]
done

**Comment by lunny** [comment]
LGTM

**Pull request merged**
