### PR TITLE
Add note Go 1.7 is required for building from source

### PR DESCRIPTION
**Pull request by cez81**
Building from source requires Go 1.7 or higher

Ref: https://github.com/go-gitea/git/blob/master/command.go#L9
https://github.com/go-gitea/gitea/pull/1470

### CODE REVIEW

**Comment by lunny** [comment]
wait until we released v1.2

**Comment by bkcsoft** [comment]
@lunny Technically it breaks now, so it should be updated now since this doc is about biulding from _source_ not our released versions.

**Comment by bkcsoft** [comment]
Anyhow, you have my LGTM for whenever

**Comment by lunny** [comment]
LGTM

**Pull request merged**
