### PR TITLE
taks --> tasks typo correction

### PR DESCRIPTION
**Pull request by tjyang**
taks --> tasks typo correction, my first attempt to submit PR for gitea project.

### CODE REVIEW

**Comment by strk** [comment]
Trust based LGTM
I cannot really see as I dont' have a GUI in front of me
and the presence of long lines make it hard to tell which word changed.
This is what I see:

```
-Since we already bundle all required libraries to build Gitea you can continue with the build process itself. We provide various [make taks](https://github.com/go-gitea/gitea/blob/master/Makefile) to keep the build process as simple as possible. Depending on your requirements you possibly want to add various build tags, you can choose between these tags:
+Since we already bundle all required libraries to build Gitea you can continue with the build process itself. We provide various [make tasks](https://github.com/go-gitea/gitea/blob/master/Makefile) to keep the build process as simple as possible. Depending on your requirements you possibly want to add various build tags, you can choose between these tags:
```

**Comment by andreynering** [comment]
LGTM

**Comment by andreynering** [comment]
Thanks

**Comment by tjyang** [comment]
Thanks for the merge. What is next step ?
I still see "make taks" on https://docs.gitea.io/en-us/install-from-source/.

**Comment by andreynering** [comment]
@jyang It changed for me. The build process of the site may take few minutes.

**Comment by tjyang** [comment]
@andreynering. Indeed, the typo is now corrected. 
Thanks

**Comment by tboerger** [comment]
@tjyang just to explain the process: every merge on master branch triggers drone ci, this builds a docker container containing the Hugo static page and pushs it to docker hub, on the server hosting the docs we got watchtower running which automatically updates and restarts docker images periodically. After that only the cdn cache need to expire to serve the new content.

**Comment by tjyang** [comment]
@tboerger, Thanks for taking time to write up the CI to CD flow details.

**Pull request merged**
