### PR TITLE
Add openid configuration values in cheatsheet

### PR DESCRIPTION
**Pull request by strk**
Now that OpenID branch was merged, these are the new
configurations available

### CODE REVIEW

**Comment by lunny** [comment]
Don't merge this after we branch v1.1

**Comment by tboerger** [comment]
LGTM

**Comment by strk** [comment]
@lunny time to merge this

**Comment by lunny** [comment]
LGTM

**Review by appleboy — APPROVED** [review]

**Comment by strk** [comment]
Make LGTM and drone work ! (and please merge this)

**Comment by appleboy** [comment]
drone pending. cc @lunny

**Pull request merged**
